# Generated by Django 3.1.7 on 2021-06-18 09:32

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210322_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='events/default.jpeg', upload_to=events.models.upload_to, verbose_name='Image'),
        ),
    ]
